spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
    hikari:
      schema: public
      maximum-pool-size: 5
      pool-name: springHikari
      connection-test-query: SELECT 1

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: false
        hbm2ddl:
          auto: create-drop
        format_sql: true

